[package]
name = "staticpendulum_rust"
version = "0.1.0"
authors = ["jbuckmccready <jbuckmccready@gmail.com>"]
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[dependencies]
time = "0.1.34"
image = "0.10.1"
